<?php

return [
    'date_format' => 'Y-m-d',
    'time_format' => 'g:i A',
    'states' => [
        1 => 'Sydney',
        2 => 'New York',
        3 => 'Amsterdam',
        4 => 'Bostone',
        5 => 'Aus State One',
        6 => 'Aus State Two',
    ],
    'job_statuses' => [
        1 => 'Lead',
        2 => 'Ready to Quote',
        3 => 'Job Quoted',
        4 => 'Ready for Inspection',
        5 => 'Job on Standby',
        6 => 'Ready To Install',
        7 => 'Job Installed',
        8 => 'Ready for Dismantle',
        9 => 'Ready for Invoicing',
        10 => 'Job Postponed',
        11 => 'Job Cancelled',
        12 => 'Invoiced',
        13 => 'Jobs Missed',
    ],
    'job_types' => [
        1 => 'Commercial',
        2 => 'Domestic',
    ],
    'event_statuses' => [
        1 => 'Scheduled',
        2 => 'On Standby',
        3 => 'Delayed',
        4 => 'Reschedule',
        5 => 'Complete',
        6 => 'Cancelled',
        7 => 'Quote',
    ],
    'event_types' => [
        1 => 'Boom Lift Only',
        2 => 'Install',
        3 => 'Dismantle',
        4 => 'Inspection',
        5 => 'On Day Hire',
        6 => 'Delivery',
    ],
    'event_vehicles' => [
        1 => 'Beavertail',
        2 => 'Hino Dutro',
        3 => 'Hino Ranger',
        4 => 'Isuzu Short',
        5 => 'Total Towing',
        6 => 'Yard',
    ],
    'install_types' => [
        1 => 'Construction',
        2 => 'Re-Roof Standard',
        3 => 'Re-Roof Pole',
        4 => 'Renovation',
        5 => 'Other',
    ],
    'roof_types' => [
        1 => 'Trimdeck',
        2 => 'Cliplock',
        3 => 'Corrugated',
        4 => 'Other',
    ],
    'platform_lengths' => [
        1 => '6m',
        2 => '5m',
        3 => '4m',
        4 => '3m',
        5 => '2m',
    ],
    'pitches' => [
        1 => 'Flat',
        2 => 'Steep',
        3 => 'Normal',
        4 => 'Other',
    ],
    'heights' => [
        1 => '1 Storey',
        2 => '2 Storey',
        3 => '3 Storey',
        4 => 'Other',
    ],
    'rows' => 5,

];